[package]
name = "shi-rs"
version = "0.24.320-alpha"
edition = "2021"
authors = ["Dallas"]
description = "Lightweight (cross-platform, in the future) package installer."

[dependencies]
casual_logger = "0.6.5"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
